`Units::teleport()`: set idle_area
DFHack/dfhack pull request #2276
Opened 2022-09-05 03:10 UTC by lethosor

Per Doublestrafe's suggestion on Discord

2022-09-07 16:15 UTC, myk002 requested changes

2022-09-07 22:17 UTC, lethosor commented on docs/changelog.txt
> +- ``Units::teleport()``: now sets ``unit.idle_area``
I don't really know why. Just wanted to move the discussion along

2022-09-24 17:46 UTC, lethosor commented on docs/changelog.txt
> +- ``Units::teleport()``: now sets ``unit.idle_area``
How's https://github.com/DFHack/dfhack/pull/2276/commits/c1b9ffc7ca7cef93ebaa0554f39a1fb40d10ef77?

2022-09-24 23:06 UTC, myk002 approved these changes

2022-09-24 23:09 UTC, merged