Implement/change/expose to Lua constructions findAtTile & insert
DFHack/dfhack pull request #2331
Opened 2022-10-12 20:12 UTC by wolfboyft

Fixes #2323

2022-10-12 20:16 UTC, myk002 requested changes

2022-10-12 20:16 UTC, myk002 commented on docs/Lua API.rst
> +  Properly inserts the given construction into the game.
be sure to note that it returns a boolean that indicates successful insertion.

2022-10-12 20:16 UTC, myk002 commented on library/LuaApi.cpp
> +    WRAPM(Constructions, insert),
the `WRAPM` line should go in the `dfhack_constructions_module` array on line 2265

2022-10-12 20:16 UTC, myk002 commented on library/modules/Constructions.cpp
> +bool Constructions::insert(df::construction * constr)
this needs a prototype in the `library/include/modules/Constructions.h` file

2022-10-12 20:32 UTC, wolfboyft commented
What? Errors? I just built it myself!

2022-10-13 01:51 UTC, myk002 commented
For the final touch, could you change the PR description to say "Fixes #2323" so the related issue gets closed when we merge this PR? Example: https://github.com/DFHack/dfhack/pull/2318

2022-10-13 13:46 UTC, myk002 commented
> Wait, don't we also need a changelog entry?

Ha, yes, yes we do.

2022-10-13 15:01 UTC, wolfboyft commented
Misc improvements for the binsearch, API for the new function, and Lua for the two newly exposed functions?

2022-10-13 15:19 UTC, myk002 commented
Sgtm

2022-10-13 19:51 UTC, wolfboyft commented
Let me know if there're any gripes with the changelog entries.

2022-10-13 20:17 UTC, wolfboyft commented
It's strange to get new compile errors when all I changed was the changelog...

2022-10-14 00:40 UTC, myk002 approved these changes

2022-10-14 00:40 UTC, merged